matrix:
  include:
    - language: node_js
      node_js:
        - '10'
        - '8'
        - '6'
      before_install:
        - cd web/
      install:
        - npm install
      script:
        - npm run lint
        - npm run build

    - language: go
      go:
        - 1.10.x
      before_install:
        - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        - dep ensure -update -v
      script:
        - ./testdata/test.sh
      after_success:
        - bash <(curl -s https://codecov.io/bash)
